version: 2
machine:
  environment:
    QEMU_AUDIO_DRV: none

test:
  pre:
    - emulator -avd circleci-android24 -no-window:
        background: true
        parallel: true
    - circle-android wait-for-boot
    # run tests  against the emulator.
    - ./gradlew connectedAndroidTest
    # copy the build outputs to artifacts
    - cp -r app/build/outputs $CIRCLE_ARTIFACTS
    # copy the test results to the test results directory.
    - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS

