name: runTestsAndBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: lint
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
